# Generated by Django 5.2.8 on 2025-11-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='ads/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('synopsis', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('video_file', models.FileField(upload_to='movies/')),
                ('is_public_domain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('ca', 'Catalán')], max_length=5)),
                ('label', models.CharField(help_text="Ej: 'Doblaje original', 'Doblaje IA 2025'", max_length=100)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('audio_file', models.FileField(upload_to='audio_tracks/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='catalog.movie')),
            ],
        ),
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('pre', 'Pre-roll'), ('mid', 'Mid-roll')], max_length=10)),
                ('timestamp_seconds', models.PositiveIntegerField(default=0, help_text='Para mid-roll, segundo donde lanzar el anuncio')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.ad')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_slots', to='catalog.movie')),
            ],
        ),
    ]
