# Generated by Django 5.2.8 on 2025-11-28 14:43

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='audio_file',
            field=models.FileField(upload_to=catalog.models.audio_track_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.movie_poster_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(upload_to=catalog.models.movie_video_path),
        ),
        migrations.AddConstraint(
            model_name='audiotrack',
            constraint=models.UniqueConstraint(fields=('movie', 'language', 'label'), name='unique_label_per_movie_language'),
        ),
    ]
